<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::query()->pluck('id', 'slug');
        $brands = Brand::query()->pluck('id', 'slug');

        $products = [
            [
                'sku' => 'PRD-1001',
                'name' => 'Apple iPhone 15 Pro 256GB',
                'brand_slug' => 'apple',
                'category_slug' => 'smartphones',
                'price' => 1099.00,
                'previous_price' => 1199.00,
                'stock' => 12,
                'rating' => 4.8,
                'review_count' => 124,
                'is_featured' => true,
                'is_new' => false,
                'image_label' => 'iPhone',
                'image_theme' => 'phone-titanium',
                'color_name' => 'Natural Titanium',
                'short_description' => 'Titanium flagship phone with Pro camera controls and A17 Pro performance.',
                'description' => 'A premium smartphone for photography, gaming, and daily productivity with a bright display, strong battery life, and durable titanium finish.',
                'shipping_weight_grams' => 187,
                'warranty_months' => 12,
                'specifications' => ['storage' => '256GB', 'display' => '6.1-inch', 'connectivity' => '5G'],
            ],
            [
                'sku' => 'PRD-1002',
                'name' => 'Samsung Galaxy S24 Ultra',
                'brand_slug' => 'samsung',
                'category_slug' => 'smartphones',
                'price' => 1299.99,
                'previous_price' => null,
                'stock' => 10,
                'rating' => 4.7,
                'review_count' => 98,
                'is_featured' => true,
                'is_new' => true,
                'image_label' => 'S24',
                'image_theme' => 'phone-graphite',
                'color_name' => 'Titanium Gray',
                'short_description' => 'Large-screen Android flagship with S Pen, AI tools, and advanced camera zoom.',
                'description' => 'A high-end Android phone built for multitasking, note taking, editing, and sharp long-range photos.',
                'shipping_weight_grams' => 232,
                'warranty_months' => 12,
                'specifications' => ['storage' => '256GB', 'display' => '6.8-inch', 'pen' => 'S Pen included'],
            ],
            [
                'sku' => 'PRD-1003',
                'name' => 'Sony WH-1000XM5 Headphones',
                'brand_slug' => 'sony',
                'category_slug' => 'audio',
                'price' => 399.99,
                'previous_price' => null,
                'stock' => 18,
                'rating' => 4.7,
                'review_count' => 210,
                'is_featured' => true,
                'is_new' => false,
                'image_label' => 'XM5',
                'image_theme' => 'audio-black',
                'color_name' => 'Black',
                'short_description' => 'Wireless noise-canceling headphones tuned for travel and deep focus.',
                'description' => 'A lightweight over-ear headset with adaptive noise cancellation, clear calls, and long battery life.',
                'shipping_weight_grams' => 250,
                'warranty_months' => 12,
                'specifications' => ['battery' => 'Up to 30 hours', 'noise_canceling' => 'Adaptive ANC', 'fit' => 'Over-ear'],
            ],
            [
                'sku' => 'PRD-1004',
                'name' => 'Apple MacBook Air 13-inch M3',
                'brand_slug' => 'apple',
                'category_slug' => 'computers',
                'price' => 1099.00,
                'previous_price' => 1199.00,
                'stock' => 8,
                'rating' => 4.9,
                'review_count' => 156,
                'is_featured' => true,
                'is_new' => true,
                'image_label' => 'Air',
                'image_theme' => 'laptop-teal',
                'color_name' => 'Midnight',
                'short_description' => 'Portable M3 laptop for study, work, and everyday creative projects.',
                'description' => 'A thin, fanless laptop with excellent battery life, a sharp display, and enough performance for everyday production work.',
                'shipping_weight_grams' => 1240,
                'warranty_months' => 12,
                'specifications' => ['chip' => 'Apple M3', 'memory' => '8GB', 'storage' => '256GB SSD'],
            ],
            [
                'sku' => 'PRD-1005',
                'name' => 'Dell XPS 13 Laptop',
                'brand_slug' => 'dell',
                'category_slug' => 'computers',
                'price' => 999.99,
                'previous_price' => null,
                'stock' => 7,
                'rating' => 4.5,
                'review_count' => 88,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'XPS',
                'image_theme' => 'laptop-silver',
                'color_name' => 'Platinum',
                'short_description' => 'Compact Windows laptop with premium build and bright display.',
                'description' => 'A sleek work laptop for browsing, spreadsheets, online classes, and travel-friendly productivity.',
                'shipping_weight_grams' => 1180,
                'warranty_months' => 12,
                'specifications' => ['display' => '13.4-inch', 'os' => 'Windows', 'storage' => '512GB SSD'],
            ],
            [
                'sku' => 'PRD-1006',
                'name' => 'Nintendo Switch OLED Model',
                'brand_slug' => 'nintendo',
                'category_slug' => 'gaming',
                'price' => 349.99,
                'previous_price' => null,
                'stock' => 15,
                'rating' => 4.8,
                'review_count' => 176,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Switch',
                'image_theme' => 'gaming-red',
                'color_name' => 'Neon Red/Blue',
                'short_description' => 'Hybrid console with vivid OLED display for TV, tabletop, and handheld play.',
                'description' => 'A flexible gaming system for family games, travel, and casual handheld sessions.',
                'shipping_weight_grams' => 420,
                'warranty_months' => 12,
                'specifications' => ['display' => '7-inch OLED', 'storage' => '64GB', 'modes' => 'TV, tabletop, handheld'],
            ],
            [
                'sku' => 'PRD-1007',
                'name' => 'Apple AirPods Pro (2nd Generation)',
                'brand_slug' => 'apple',
                'category_slug' => 'audio',
                'price' => 249.00,
                'previous_price' => null,
                'stock' => 22,
                'rating' => 4.8,
                'review_count' => 242,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Pods',
                'image_theme' => 'earbuds-white',
                'color_name' => 'White',
                'short_description' => 'Compact earbuds with active noise cancellation and spatial audio.',
                'description' => 'Everyday earbuds for calls, commuting, workouts, and seamless switching between Apple devices.',
                'shipping_weight_grams' => 61,
                'warranty_months' => 12,
                'specifications' => ['case' => 'MagSafe charging', 'noise_canceling' => 'Active ANC', 'fit' => 'In-ear'],
            ],
            [
                'sku' => 'PRD-1008',
                'name' => 'Samsung 55-inch Class QLED 4K TV',
                'brand_slug' => 'samsung',
                'category_slug' => 'tv-home-theater',
                'price' => 799.99,
                'previous_price' => 899.99,
                'stock' => 6,
                'rating' => 4.6,
                'review_count' => 73,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'QLED',
                'image_theme' => 'tv-blue',
                'color_name' => 'Black',
                'short_description' => '55-inch QLED 4K TV with bright color and smart streaming apps.',
                'description' => 'A living-room screen for movies, sports, games, and streaming with crisp 4K resolution.',
                'shipping_weight_grams' => 15800,
                'warranty_months' => 24,
                'specifications' => ['size' => '55-inch', 'resolution' => '4K UHD', 'panel' => 'QLED'],
            ],
            [
                'sku' => 'PRD-1009',
                'name' => 'Bose QuietComfort Ultra Earbuds',
                'brand_slug' => 'bose',
                'category_slug' => 'audio',
                'price' => 299.00,
                'previous_price' => null,
                'stock' => 14,
                'rating' => 4.5,
                'review_count' => 67,
                'is_featured' => false,
                'is_new' => true,
                'image_label' => 'Bose',
                'image_theme' => 'earbuds-black',
                'color_name' => 'Black',
                'short_description' => 'Premium earbuds with immersive audio and strong noise cancellation.',
                'description' => 'A travel-ready listening option for music, calls, podcasts, and quieter commutes.',
                'shipping_weight_grams' => 74,
                'warranty_months' => 12,
                'specifications' => ['audio' => 'Immersive audio', 'noise_canceling' => 'QuietComfort ANC', 'fit' => 'In-ear'],
            ],
            [
                'sku' => 'PRD-1010',
                'name' => 'GoPro HERO12 Black',
                'brand_slug' => 'gopro',
                'category_slug' => 'cameras',
                'price' => 399.99,
                'previous_price' => null,
                'stock' => 9,
                'rating' => 4.4,
                'review_count' => 59,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'HERO',
                'image_theme' => 'camera-black',
                'color_name' => 'Black',
                'short_description' => 'Durable action camera for travel, sports, and outdoor video.',
                'description' => 'A rugged camera for stabilized video, slow motion clips, and compact content capture.',
                'shipping_weight_grams' => 154,
                'warranty_months' => 12,
                'specifications' => ['video' => '5.3K', 'waterproof' => '10m', 'stabilization' => 'HyperSmooth'],
            ],
            [
                'sku' => 'PRD-1011',
                'name' => 'Kindle Paperwhite 16GB',
                'brand_slug' => 'amazon',
                'category_slug' => 'e-readers',
                'price' => 149.99,
                'previous_price' => null,
                'stock' => 20,
                'rating' => 4.7,
                'review_count' => 138,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Kindle',
                'image_theme' => 'tablet-green',
                'color_name' => 'Black',
                'short_description' => 'Water-resistant e-reader with glare-free display and weeks of battery.',
                'description' => 'A lightweight reading device for travel, bedtime, and focused reading without phone distractions.',
                'shipping_weight_grams' => 205,
                'warranty_months' => 12,
                'specifications' => ['storage' => '16GB', 'display' => '6.8-inch', 'water_resistant' => 'IPX8'],
            ],
            [
                'sku' => 'PRD-1012',
                'name' => 'Logitech MX Master 3S Mouse',
                'brand_slug' => 'logitech',
                'category_slug' => 'accessories',
                'price' => 99.99,
                'previous_price' => null,
                'stock' => 30,
                'rating' => 4.9,
                'review_count' => 301,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'MX',
                'image_theme' => 'accessory-gray',
                'color_name' => 'Graphite',
                'short_description' => 'Ergonomic wireless mouse with quiet clicks and precision scrolling.',
                'description' => 'A productivity mouse for designers, analysts, and students who move between multiple devices.',
                'shipping_weight_grams' => 141,
                'warranty_months' => 24,
                'specifications' => ['dpi' => '8000', 'buttons' => '7', 'connectivity' => 'Bluetooth/USB receiver'],
            ],
            [
                'sku' => 'PRD-1013',
                'name' => 'PlayStation 5 Console',
                'brand_slug' => 'sony',
                'category_slug' => 'gaming',
                'price' => 499.99,
                'previous_price' => null,
                'stock' => 11,
                'rating' => 4.8,
                'review_count' => 190,
                'is_featured' => true,
                'is_new' => false,
                'image_label' => 'PS5',
                'image_theme' => 'console-white',
                'color_name' => 'White',
                'short_description' => 'Current-generation console for cinematic games and fast loading.',
                'description' => 'A home console with strong graphics performance, haptic controller feedback, and a broad game library.',
                'shipping_weight_grams' => 4500,
                'warranty_months' => 12,
                'specifications' => ['storage' => '1TB', 'resolution' => 'Up to 4K', 'controller' => 'DualSense'],
            ],
            [
                'sku' => 'PRD-1014',
                'name' => 'Xbox Series X',
                'brand_slug' => 'microsoft',
                'category_slug' => 'gaming',
                'price' => 499.99,
                'previous_price' => null,
                'stock' => 9,
                'rating' => 4.7,
                'review_count' => 112,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Xbox',
                'image_theme' => 'console-black',
                'color_name' => 'Black',
                'short_description' => 'Powerful console with Game Pass support and fast resume.',
                'description' => 'A high-performance console for 4K gaming, media streaming, and subscription game libraries.',
                'shipping_weight_grams' => 4450,
                'warranty_months' => 12,
                'specifications' => ['storage' => '1TB', 'resolution' => 'Up to 4K', 'service' => 'Game Pass ready'],
            ],
            [
                'sku' => 'PRD-1015',
                'name' => 'Dyson V15 Detect Vacuum',
                'brand_slug' => 'dyson',
                'category_slug' => 'home-kitchen',
                'price' => 749.99,
                'previous_price' => 799.99,
                'stock' => 5,
                'rating' => 4.6,
                'review_count' => 64,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'V15',
                'image_theme' => 'home-gold',
                'color_name' => 'Nickel/Yellow',
                'short_description' => 'Cordless vacuum with dust detection and powerful suction.',
                'description' => 'A premium cleaning tool for carpets, hard floors, pet hair, and quick everyday messes.',
                'shipping_weight_grams' => 3100,
                'warranty_months' => 24,
                'specifications' => ['runtime' => 'Up to 60 minutes', 'type' => 'Cordless', 'sensor' => 'Dust detection'],
            ],
            [
                'sku' => 'PRD-1016',
                'name' => 'Instant Pot Duo 7-in-1 6 Quart',
                'brand_slug' => 'instant-pot',
                'category_slug' => 'home-kitchen',
                'price' => 99.95,
                'previous_price' => null,
                'stock' => 16,
                'rating' => 4.7,
                'review_count' => 218,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Duo',
                'image_theme' => 'kitchen-silver',
                'color_name' => 'Stainless Steel',
                'short_description' => 'Multi-cooker for pressure cooking, slow cooking, rice, and steaming.',
                'description' => 'A practical kitchen appliance for meal prep, family dinners, and compact kitchens.',
                'shipping_weight_grams' => 5200,
                'warranty_months' => 12,
                'specifications' => ['capacity' => '6 quart', 'functions' => '7-in-1', 'finish' => 'Stainless steel'],
            ],
            [
                'sku' => 'PRD-1017',
                'name' => 'Ninja Foodi DualZone Air Fryer',
                'brand_slug' => 'ninja',
                'category_slug' => 'home-kitchen',
                'price' => 199.99,
                'previous_price' => null,
                'stock' => 13,
                'rating' => 4.6,
                'review_count' => 147,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Foodi',
                'image_theme' => 'kitchen-black',
                'color_name' => 'Black',
                'short_description' => 'Dual-basket air fryer for cooking two foods at once.',
                'description' => 'A countertop cooker with two independent baskets for fast weeknight meals and snacks.',
                'shipping_weight_grams' => 8200,
                'warranty_months' => 12,
                'specifications' => ['capacity' => '8 quart', 'zones' => '2', 'finish' => 'Black'],
            ],
            [
                'sku' => 'PRD-1018',
                'name' => 'Garmin Forerunner 265',
                'brand_slug' => 'garmin',
                'category_slug' => 'wearables',
                'price' => 449.99,
                'previous_price' => null,
                'stock' => 8,
                'rating' => 4.5,
                'review_count' => 82,
                'is_featured' => false,
                'is_new' => true,
                'image_label' => '265',
                'image_theme' => 'watch-blue',
                'color_name' => 'Aqua',
                'short_description' => 'GPS running watch with AMOLED display and training readiness.',
                'description' => 'A sports watch for runners who want guided workouts, recovery data, and daily health tracking.',
                'shipping_weight_grams' => 47,
                'warranty_months' => 12,
                'specifications' => ['display' => 'AMOLED', 'gps' => 'Multi-band', 'battery' => 'Up to 13 days'],
            ],
            [
                'sku' => 'PRD-1019',
                'name' => 'Canon EOS R50 Mirrorless Camera',
                'brand_slug' => 'canon',
                'category_slug' => 'cameras',
                'price' => 679.99,
                'previous_price' => null,
                'stock' => 6,
                'rating' => 4.4,
                'review_count' => 51,
                'is_featured' => false,
                'is_new' => true,
                'image_label' => 'R50',
                'image_theme' => 'camera-silver',
                'color_name' => 'Black',
                'short_description' => 'Compact mirrorless camera for creators, travel, and family photos.',
                'description' => 'A lightweight interchangeable-lens camera with sharp autofocus and strong video features.',
                'shipping_weight_grams' => 375,
                'warranty_months' => 12,
                'specifications' => ['sensor' => 'APS-C', 'video' => '4K', 'lens' => 'RF-S mount'],
            ],
            [
                'sku' => 'PRD-1020',
                'name' => 'LEGO Icons Bouquet of Roses',
                'brand_slug' => 'lego',
                'category_slug' => 'toys',
                'price' => 59.99,
                'previous_price' => null,
                'stock' => 24,
                'rating' => 4.9,
                'review_count' => 89,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'LEGO',
                'image_theme' => 'toy-red',
                'color_name' => 'Red',
                'short_description' => 'Decorative building set with rose stems for gifting or display.',
                'description' => 'A relaxing creative set for adults and older builders who want a colorful display piece.',
                'shipping_weight_grams' => 760,
                'warranty_months' => null,
                'specifications' => ['pieces' => '822', 'age' => '18+', 'theme' => 'Icons'],
            ],
        ];

        $products = array_merge($products, $this->additionalRealProducts());

        foreach ($products as $product) {
            $categorySlug = $product['category_slug'];
            $brandSlug = $product['brand_slug'];

            unset($product['category_slug'], $product['brand_slug']);

            $product['category_id'] = $categories[$categorySlug] ?? null;
            $product['brand_id'] = $brands[$brandSlug] ?? null;
            $product['category'] = Category::query()->whereKey($product['category_id'])->value('name') ?? 'Uncategorized';
            $product['brand'] = Brand::query()->whereKey($product['brand_id'])->value('name') ?? 'Generic';
            $product['return_window_days'] = 30;
            $product['published_at'] = now()->subDays(7);
            $product['is_active'] = true;

            Product::query()->updateOrCreate(
                ['sku' => $product['sku']],
                $product,
            );
        }
    }

    private function additionalRealProducts(): array
    {
        $items = [
            ['apple', 'smartphones', 'Apple iPhone 15 128GB', 799.00, 'phone-titanium', 'iPhone'],
            ['apple', 'smartphones', 'Apple iPhone 15 Plus 128GB', 899.00, 'phone-titanium', 'iPhone'],
            ['apple', 'smartphones', 'Apple iPhone 15 Pro Max 256GB', 1199.00, 'phone-titanium', 'Pro Max'],
            ['apple', 'smartphones', 'Apple iPhone 14 128GB', 699.00, 'phone-titanium', 'iPhone'],
            ['apple', 'smartphones', 'Apple iPhone 13 128GB', 599.00, 'phone-titanium', 'iPhone'],
            ['samsung', 'smartphones', 'Samsung Galaxy S24', 799.99, 'phone-graphite', 'S24'],
            ['samsung', 'smartphones', 'Samsung Galaxy S24+', 999.99, 'phone-graphite', 'S24+'],
            ['samsung', 'smartphones', 'Samsung Galaxy S23 FE', 599.99, 'phone-graphite', 'S23 FE'],
            ['samsung', 'smartphones', 'Samsung Galaxy Z Fold5', 1799.99, 'phone-graphite', 'Fold5'],
            ['samsung', 'smartphones', 'Samsung Galaxy Z Flip5', 999.99, 'phone-graphite', 'Flip5'],
            ['google', 'smartphones', 'Google Pixel 8 128GB', 699.00, 'phone-graphite', 'Pixel 8'],
            ['google', 'smartphones', 'Google Pixel 8 Pro 128GB', 999.00, 'phone-graphite', 'Pixel Pro'],
            ['google', 'smartphones', 'Google Pixel 8a 128GB', 499.00, 'phone-graphite', 'Pixel 8a'],
            ['oneplus', 'smartphones', 'OnePlus 12 256GB', 799.99, 'phone-graphite', 'OnePlus'],
            ['oneplus', 'smartphones', 'OnePlus Open 512GB', 1699.99, 'phone-graphite', 'Open'],
            ['motorola', 'smartphones', 'Motorola razr+ 2023', 999.99, 'phone-graphite', 'razr+'],
            ['motorola', 'smartphones', 'Motorola Edge+ 2023', 799.99, 'phone-graphite', 'Edge+'],
            ['apple', 'smartphones', 'Apple iPhone SE 64GB', 429.00, 'phone-titanium', 'SE'],
            ['samsung', 'smartphones', 'Samsung Galaxy A54 5G', 449.99, 'phone-graphite', 'A54'],
            ['google', 'smartphones', 'Google Pixel Fold', 1799.00, 'phone-graphite', 'Fold'],
            ['apple', 'computers', 'Apple MacBook Air 15-inch M3', 1299.00, 'laptop-teal', 'Air 15'],
            ['apple', 'computers', 'Apple MacBook Pro 14-inch M3', 1599.00, 'laptop-teal', 'MBP 14'],
            ['apple', 'computers', 'Apple MacBook Pro 16-inch M3 Pro', 2499.00, 'laptop-teal', 'MBP 16'],
            ['apple', 'computers', 'Apple iMac 24-inch M3', 1299.00, 'laptop-teal', 'iMac'],
            ['apple', 'computers', 'Apple Mac mini M2', 599.00, 'laptop-teal', 'Mac mini'],
            ['dell', 'computers', 'Dell XPS 15 Laptop', 1499.99, 'laptop-silver', 'XPS 15'],
            ['dell', 'computers', 'Dell XPS 16 Laptop', 1899.99, 'laptop-silver', 'XPS 16'],
            ['dell', 'computers', 'Dell Inspiron 15 Laptop', 529.99, 'laptop-silver', 'Inspiron'],
            ['dell', 'computers', 'Dell Alienware m16 R2 Gaming Laptop', 1699.99, 'laptop-silver', 'm16'],
            ['lenovo', 'computers', 'Lenovo ThinkPad X1 Carbon Gen 12', 1799.00, 'laptop-silver', 'X1'],
            ['lenovo', 'computers', 'Lenovo Yoga 7i 14-inch', 849.99, 'laptop-silver', 'Yoga'],
            ['lenovo', 'computers', 'Lenovo Legion Pro 5i', 1499.99, 'laptop-silver', 'Legion'],
            ['hp', 'computers', 'HP Spectre x360 14', 1399.99, 'laptop-silver', 'Spectre'],
            ['hp', 'computers', 'HP Envy x360 15', 799.99, 'laptop-silver', 'Envy'],
            ['hp', 'computers', 'HP Pavilion Plus 14', 899.99, 'laptop-silver', 'Pavilion'],
            ['asus', 'computers', 'ASUS Zenbook 14 OLED', 999.99, 'laptop-silver', 'Zenbook'],
            ['asus', 'computers', 'ASUS ROG Zephyrus G14', 1599.99, 'laptop-silver', 'G14'],
            ['asus', 'computers', 'ASUS TUF Gaming A15', 1099.99, 'laptop-silver', 'TUF'],
            ['acer', 'computers', 'Acer Swift Go 14', 849.99, 'laptop-silver', 'Swift'],
            ['acer', 'computers', 'Acer Chromebook Spin 714', 699.99, 'laptop-silver', 'Spin'],
            ['apple', 'computers', 'Apple iPad Pro 11-inch M4', 999.00, 'tablet-green', 'iPad Pro'],
            ['apple', 'computers', 'Apple iPad Air 11-inch M2', 599.00, 'tablet-green', 'iPad Air'],
            ['samsung', 'computers', 'Samsung Galaxy Tab S9 Ultra', 1199.99, 'tablet-green', 'Tab S9'],
            ['microsoft', 'computers', 'Microsoft Surface Laptop 6', 1199.99, 'laptop-silver', 'Surface'],
            ['microsoft', 'computers', 'Microsoft Surface Pro 10', 1199.99, 'tablet-green', 'Surface'],
            ['sony', 'audio', 'Sony WF-1000XM5 Earbuds', 299.99, 'earbuds-black', 'WF-XM5'],
            ['sony', 'audio', 'Sony WH-1000XM4 Headphones', 349.99, 'audio-black', 'XM4'],
            ['sony', 'audio', 'Sony ULT Wear Headphones', 199.99, 'audio-black', 'ULT'],
            ['apple', 'audio', 'Apple AirPods Max', 549.00, 'audio-black', 'AirPods'],
            ['apple', 'audio', 'Apple AirPods (3rd Generation)', 169.00, 'earbuds-white', 'AirPods'],
            ['beats', 'audio', 'Beats Studio Pro Headphones', 349.99, 'audio-black', 'Beats'],
            ['beats', 'audio', 'Beats Fit Pro Earbuds', 199.99, 'earbuds-black', 'Fit Pro'],
            ['bose', 'audio', 'Bose QuietComfort Headphones', 349.00, 'audio-black', 'QC'],
            ['bose', 'audio', 'Bose SoundLink Flex Speaker', 149.00, 'audio-black', 'Flex'],
            ['jbl', 'audio', 'JBL Charge 5 Speaker', 179.95, 'audio-black', 'Charge'],
            ['jbl', 'audio', 'JBL Flip 6 Speaker', 129.95, 'audio-black', 'Flip'],
            ['jbl', 'audio', 'JBL Live 770NC Headphones', 199.95, 'audio-black', '770NC'],
            ['sennheiser', 'audio', 'Sennheiser Momentum 4 Wireless', 379.95, 'audio-black', 'M4'],
            ['sennheiser', 'audio', 'Sennheiser Momentum True Wireless 4', 299.95, 'earbuds-black', 'MTW4'],
            ['marshall', 'audio', 'Marshall Major IV Headphones', 149.99, 'audio-black', 'Major'],
            ['marshall', 'audio', 'Marshall Emberton II Speaker', 169.99, 'audio-black', 'Emberton'],
            ['anker', 'audio', 'Anker Soundcore Liberty 4 NC', 99.99, 'earbuds-black', 'Liberty'],
            ['anker', 'audio', 'Anker Soundcore Motion X600 Speaker', 199.99, 'audio-black', 'X600'],
            ['logitech', 'audio', 'Logitech G Pro X 2 Lightspeed Headset', 249.99, 'audio-black', 'G Pro'],
            ['microsoft', 'audio', 'Microsoft Xbox Wireless Headset', 99.99, 'audio-black', 'Xbox'],
            ['samsung', 'audio', 'Samsung Galaxy Buds2 Pro', 229.99, 'earbuds-white', 'Buds2'],
            ['google', 'audio', 'Google Pixel Buds Pro', 199.99, 'earbuds-white', 'Buds'],
            ['razer', 'audio', 'Razer BlackShark V2 Pro Headset', 199.99, 'audio-black', 'V2 Pro'],
            ['sony', 'tv-home-theater', 'Sony Bravia XR A80L OLED 55-inch TV', 1699.99, 'tv-blue', 'Bravia'],
            ['sony', 'tv-home-theater', 'Sony HT-A5000 Soundbar', 999.99, 'audio-black', 'HT-A5000'],
            ['samsung', 'tv-home-theater', 'Samsung 65-inch The Frame QLED TV', 1999.99, 'tv-blue', 'Frame'],
            ['samsung', 'tv-home-theater', 'Samsung HW-Q990C Soundbar', 1599.99, 'audio-black', 'Q990C'],
            ['lg', 'tv-home-theater', 'LG C3 55-inch OLED evo TV', 1499.99, 'tv-blue', 'LG C3'],
            ['lg', 'tv-home-theater', 'LG G3 65-inch OLED evo TV', 2499.99, 'tv-blue', 'LG G3'],
            ['lg', 'tv-home-theater', 'LG S95QR Soundbar', 1499.99, 'audio-black', 'S95QR'],
            ['tcl', 'tv-home-theater', 'TCL 65-inch QM8 QLED TV', 1199.99, 'tv-blue', 'QM8'],
            ['tcl', 'tv-home-theater', 'TCL 55-inch Q7 QLED TV', 599.99, 'tv-blue', 'Q7'],
            ['hisense', 'tv-home-theater', 'Hisense 65-inch U8K Mini-LED TV', 1099.99, 'tv-blue', 'U8K'],
            ['hisense', 'tv-home-theater', 'Hisense 55-inch U7K ULED TV', 649.99, 'tv-blue', 'U7K'],
            ['amazon', 'tv-home-theater', 'Amazon Fire TV Stick 4K Max', 59.99, 'tablet-green', 'Fire TV'],
            ['apple', 'tv-home-theater', 'Apple TV 4K Wi-Fi 64GB', 129.00, 'tablet-green', 'Apple TV'],
            ['google', 'tv-home-theater', 'Chromecast with Google TV 4K', 49.99, 'tablet-green', 'Cast'],
            ['bose', 'tv-home-theater', 'Bose Smart Soundbar 600', 499.00, 'audio-black', 'Bose'],
            ['sony', 'gaming', 'PlayStation Portal Remote Player', 199.99, 'console-white', 'Portal'],
        ];

        $items = array_merge($items, [
            ['sony', 'gaming', 'PlayStation 5 Digital Edition', 449.99, 'console-white', 'PS5'],
            ['sony', 'gaming', 'DualSense Wireless Controller', 69.99, 'console-white', 'DualSense'],
            ['microsoft', 'gaming', 'Xbox Series S 512GB', 299.99, 'console-white', 'Series S'],
            ['microsoft', 'gaming', 'Xbox Wireless Controller', 64.99, 'console-black', 'Xbox'],
            ['nintendo', 'gaming', 'Nintendo Switch Lite', 199.99, 'gaming-red', 'Switch'],
            ['nintendo', 'gaming', 'Nintendo Switch Joy-Con Pair', 79.99, 'gaming-red', 'Joy-Con'],
            ['valve', 'gaming', 'Steam Deck OLED 512GB', 549.00, 'console-black', 'Steam'],
            ['razer', 'gaming', 'Razer Kishi V2 Mobile Controller', 99.99, 'console-black', 'Kishi'],
            ['razer', 'gaming', 'Razer Wolverine V2 Chroma Controller', 149.99, 'console-black', 'Wolverine'],
            ['meta', 'gaming', 'Meta Quest 3 128GB', 499.99, 'console-white', 'Quest 3'],
            ['logitech', 'gaming', 'Logitech G Cloud Gaming Handheld', 299.99, 'console-white', 'G Cloud'],
            ['asus', 'gaming', 'ASUS ROG Ally Z1 Extreme', 699.99, 'console-white', 'ROG Ally'],
            ['lenovo', 'gaming', 'Lenovo Legion Go', 699.99, 'console-black', 'Legion'],
            ['steelseries', 'gaming', 'SteelSeries Arctis Nova 7 Wireless', 179.99, 'audio-black', 'Arctis'],
            ['logitech', 'gaming', 'Logitech G502 X Plus Mouse', 159.99, 'accessory-gray', 'G502'],
            ['razer', 'gaming', 'Razer DeathAdder V3 Pro Mouse', 149.99, 'accessory-gray', 'Razer'],
            ['canon', 'cameras', 'Canon EOS R8 Mirrorless Camera', 1499.99, 'camera-silver', 'R8'],
            ['canon', 'cameras', 'Canon EOS R10 Mirrorless Camera', 979.99, 'camera-silver', 'R10'],
            ['canon', 'cameras', 'Canon PowerShot V10', 429.99, 'camera-silver', 'V10'],
            ['sony', 'cameras', 'Sony Alpha a7 IV Mirrorless Camera', 2499.99, 'camera-black', 'a7 IV'],
            ['sony', 'cameras', 'Sony ZV-E10 Mirrorless Camera', 699.99, 'camera-black', 'ZV-E10'],
            ['sony', 'cameras', 'Sony ZV-1 II Compact Camera', 899.99, 'camera-black', 'ZV-1'],
            ['nikon', 'cameras', 'Nikon Z 6II Mirrorless Camera', 1999.95, 'camera-black', 'Z 6II'],
            ['nikon', 'cameras', 'Nikon Z fc Mirrorless Camera', 959.95, 'camera-black', 'Z fc'],
            ['nikon', 'cameras', 'Nikon COOLPIX P950', 799.95, 'camera-black', 'P950'],
            ['fujifilm', 'cameras', 'Fujifilm X-T5 Mirrorless Camera', 1699.95, 'camera-silver', 'X-T5'],
            ['fujifilm', 'cameras', 'Fujifilm X100VI Digital Camera', 1599.95, 'camera-silver', 'X100VI'],
            ['fujifilm', 'cameras', 'Fujifilm Instax Mini 12', 79.95, 'camera-silver', 'Instax'],
            ['gopro', 'cameras', 'GoPro HERO11 Black', 349.99, 'camera-black', 'HERO11'],
            ['gopro', 'cameras', 'GoPro MAX 360 Camera', 499.99, 'camera-black', 'MAX'],
            ['insta360', 'cameras', 'Insta360 X4 360 Action Camera', 499.99, 'camera-black', 'X4'],
            ['insta360', 'cameras', 'Insta360 GO 3S Action Camera', 399.99, 'camera-black', 'GO 3S'],
            ['amazon', 'e-readers', 'Kindle 16GB', 99.99, 'tablet-green', 'Kindle'],
            ['amazon', 'e-readers', 'Kindle Scribe 16GB', 339.99, 'tablet-green', 'Scribe'],
            ['amazon', 'e-readers', 'Kindle Oasis 32GB', 279.99, 'tablet-green', 'Oasis'],
            ['kobo', 'e-readers', 'Kobo Clara BW', 129.99, 'tablet-green', 'Clara'],
            ['kobo', 'e-readers', 'Kobo Clara Colour', 149.99, 'tablet-green', 'Clara'],
            ['kobo', 'e-readers', 'Kobo Libra Colour', 219.99, 'tablet-green', 'Libra'],
            ['kobo', 'e-readers', 'Kobo Sage', 269.99, 'tablet-green', 'Sage'],
            ['kobo', 'e-readers', 'Kobo Elipsa 2E', 399.99, 'tablet-green', 'Elipsa'],
            ['amazon', 'e-readers', 'Kindle Kids 16GB', 119.99, 'tablet-green', 'Kids'],
            ['amazon', 'e-readers', 'Kindle Paperwhite Kids 16GB', 169.99, 'tablet-green', 'Kids'],
            ['logitech', 'accessories', 'Logitech MX Keys S Keyboard', 109.99, 'accessory-gray', 'MX Keys'],
            ['logitech', 'accessories', 'Logitech Lift Vertical Mouse', 69.99, 'accessory-gray', 'Lift'],
            ['logitech', 'accessories', 'Logitech Brio 4K Webcam', 199.99, 'accessory-gray', 'Brio'],
            ['apple', 'accessories', 'Apple Magic Keyboard with Touch ID', 149.00, 'accessory-gray', 'Magic'],
            ['apple', 'accessories', 'Apple Magic Mouse', 79.00, 'accessory-gray', 'Mouse'],
            ['apple', 'accessories', 'Apple Pencil Pro', 129.00, 'accessory-gray', 'Pencil'],
            ['samsung', 'accessories', 'Samsung T7 Shield 1TB Portable SSD', 109.99, 'accessory-gray', 'T7'],
            ['sandisk', 'accessories', 'SanDisk Extreme Portable SSD 1TB', 119.99, 'accessory-gray', 'SSD'],
            ['anker', 'accessories', 'Anker 737 Power Bank', 149.99, 'accessory-gray', '737'],
            ['anker', 'accessories', 'Anker 735 Charger', 59.99, 'accessory-gray', '735'],
            ['anker', 'accessories', 'Anker MagGo 3-in-1 Charging Station', 109.99, 'accessory-gray', 'MagGo'],
            ['belkin', 'accessories', 'Belkin BoostCharge Pro 3-in-1 Stand', 149.99, 'accessory-gray', 'Belkin'],
            ['belkin', 'accessories', 'Belkin Thunderbolt 4 Dock Pro', 399.99, 'accessory-gray', 'Dock'],
            ['microsoft', 'accessories', 'Microsoft Surface Arc Mouse', 79.99, 'accessory-gray', 'Arc'],
            ['razer', 'accessories', 'Razer Basilisk V3 Mouse', 69.99, 'accessory-gray', 'Basilisk'],
            ['jbl', 'accessories', 'JBL Quantum Stream Microphone', 99.95, 'accessory-gray', 'Quantum'],
            ['google', 'accessories', 'Google Nest Wifi Pro', 199.99, 'accessory-gray', 'Nest'],
            ['tp-link', 'accessories', 'TP-Link Deco XE75 Mesh WiFi 6E', 299.99, 'accessory-gray', 'Deco'],
            ['ubiquiti', 'accessories', 'Ubiquiti UniFi Dream Router', 199.00, 'accessory-gray', 'UniFi'],
            ['amazon', 'accessories', 'Amazon Echo Show 8', 149.99, 'tablet-green', 'Echo'],
        ]);

        $items = array_merge($items, [
            ['dyson', 'home-kitchen', 'Dyson Purifier Cool TP07', 649.99, 'home-gold', 'TP07'],
            ['dyson', 'home-kitchen', 'Dyson Airwrap Multi-Styler', 599.99, 'home-gold', 'Airwrap'],
            ['dyson', 'home-kitchen', 'Dyson Supersonic Hair Dryer', 429.99, 'home-gold', 'Dyson'],
            ['shark', 'home-kitchen', 'Shark Stratos Cordless Vacuum', 499.99, 'home-gold', 'Stratos'],
            ['shark', 'home-kitchen', 'Shark FlexStyle Air Styling System', 299.99, 'home-gold', 'Flex'],
            ['irobot', 'home-kitchen', 'iRobot Roomba j7+', 799.99, 'home-gold', 'Roomba'],
            ['irobot', 'home-kitchen', 'iRobot Braava Jet m6', 449.99, 'home-gold', 'Braava'],
            ['instant-pot', 'home-kitchen', 'Instant Pot Pro 10-in-1 6 Quart', 169.99, 'kitchen-silver', 'Pro'],
            ['instant-pot', 'home-kitchen', 'Instant Pot Vortex Plus Air Fryer', 129.99, 'kitchen-black', 'Vortex'],
            ['ninja', 'home-kitchen', 'Ninja Creami Deluxe', 249.99, 'kitchen-black', 'Creami'],
            ['ninja', 'home-kitchen', 'Ninja Woodfire Outdoor Grill', 369.99, 'kitchen-black', 'Woodfire'],
            ['kitchenaid', 'home-kitchen', 'KitchenAid Artisan Series 5-Quart Stand Mixer', 449.99, 'kitchen-silver', 'Mixer'],
            ['kitchenaid', 'home-kitchen', 'KitchenAid 3.5 Cup Food Chopper', 59.99, 'kitchen-silver', 'Chopper'],
            ['philips', 'home-kitchen', 'Philips 3200 Series Fully Automatic Espresso Machine', 799.99, 'kitchen-silver', 'Philips'],
            ['philips', 'home-kitchen', 'Philips Sonicare DiamondClean 9000', 199.99, 'kitchen-silver', 'Sonicare'],
            ['breville', 'home-kitchen', 'Breville Barista Express Espresso Machine', 699.95, 'kitchen-silver', 'Barista'],
            ['breville', 'home-kitchen', 'Breville Smart Oven Air Fryer Pro', 399.95, 'kitchen-silver', 'Oven'],
            ['google', 'home-kitchen', 'Google Nest Hub Max', 229.00, 'tablet-green', 'Nest Hub'],
            ['ring', 'home-kitchen', 'Ring Video Doorbell Pro 2', 249.99, 'accessory-gray', 'Ring'],
            ['arlo', 'home-kitchen', 'Arlo Pro 5S 2K Security Camera', 249.99, 'camera-black', 'Arlo'],
            ['apple', 'wearables', 'Apple Watch Series 9 GPS 45mm', 429.00, 'watch-blue', 'Watch'],
            ['apple', 'wearables', 'Apple Watch Ultra 2', 799.00, 'watch-blue', 'Ultra'],
            ['apple', 'wearables', 'Apple Watch SE GPS 40mm', 249.00, 'watch-blue', 'SE'],
            ['samsung', 'wearables', 'Samsung Galaxy Watch6 Classic 43mm', 399.99, 'watch-blue', 'Watch6'],
            ['samsung', 'wearables', 'Samsung Galaxy Watch6 40mm', 299.99, 'watch-blue', 'Watch6'],
            ['google', 'wearables', 'Google Pixel Watch 2', 349.99, 'watch-blue', 'Pixel'],
            ['fitbit', 'wearables', 'Fitbit Charge 6', 159.95, 'watch-blue', 'Charge'],
            ['fitbit', 'wearables', 'Fitbit Versa 4', 199.95, 'watch-blue', 'Versa'],
            ['fitbit', 'wearables', 'Fitbit Inspire 3', 99.95, 'watch-blue', 'Inspire'],
            ['garmin', 'wearables', 'Garmin Venu 3', 449.99, 'watch-blue', 'Venu'],
            ['garmin', 'wearables', 'Garmin Forerunner 965', 599.99, 'watch-blue', '965'],
            ['garmin', 'wearables', 'Garmin Fenix 7 Pro', 799.99, 'watch-blue', 'Fenix'],
            ['garmin', 'wearables', 'Garmin Instinct 2 Solar', 399.99, 'watch-blue', 'Instinct'],
            ['samsung', 'wearables', 'Samsung Galaxy Fit3', 59.99, 'watch-blue', 'Fit3'],
            ['meta', 'wearables', 'Ray-Ban Meta Wayfarer Smart Glasses', 299.00, 'watch-blue', 'Meta'],
            ['lego', 'toys', 'LEGO Icons Bonsai Tree', 49.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Ideas The Starry Night', 169.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Technic NASA Mars Rover Perseverance', 99.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Star Wars Millennium Falcon', 849.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Architecture Statue of Liberty', 119.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Icons Atari 2600', 239.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Ideas Polaroid OneStep SX-70 Camera', 79.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Icons Retro Radio', 99.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Technic Yamaha MT-10 SP', 239.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Icons Natural History Museum', 299.99, 'toy-red', 'LEGO'],
        ]);

        $items = array_merge($items, [
            ['apple', 'smartphones', 'Apple iPhone 14 Plus 128GB', 799.00, 'phone-titanium', 'iPhone'],
            ['apple', 'smartphones', 'Apple iPhone 12 64GB', 499.00, 'phone-titanium', 'iPhone'],
            ['samsung', 'smartphones', 'Samsung Galaxy S23 128GB', 699.99, 'phone-graphite', 'S23'],
            ['samsung', 'smartphones', 'Samsung Galaxy S23 Ultra 256GB', 1199.99, 'phone-graphite', 'S23 Ultra'],
            ['samsung', 'smartphones', 'Samsung Galaxy A35 5G', 399.99, 'phone-graphite', 'A35'],
            ['samsung', 'smartphones', 'Samsung Galaxy A15 5G', 199.99, 'phone-graphite', 'A15'],
            ['samsung', 'smartphones', 'Samsung Galaxy Z Fold4', 1799.99, 'phone-graphite', 'Fold4'],
            ['google', 'smartphones', 'Google Pixel 7a 128GB', 499.00, 'phone-graphite', 'Pixel 7a'],
            ['google', 'smartphones', 'Google Pixel 7 Pro 128GB', 899.00, 'phone-graphite', 'Pixel 7'],
            ['oneplus', 'smartphones', 'OnePlus Nord N30 5G', 299.99, 'phone-graphite', 'Nord'],
            ['oneplus', 'smartphones', 'OnePlus 11 256GB', 699.99, 'phone-graphite', 'OnePlus'],
            ['motorola', 'smartphones', 'Motorola Moto G Power 5G 2024', 299.99, 'phone-graphite', 'Moto G'],
            ['motorola', 'smartphones', 'Motorola Moto G Stylus 5G 2024', 399.99, 'phone-graphite', 'Stylus'],
            ['motorola', 'smartphones', 'Motorola razr 2024', 699.99, 'phone-graphite', 'razr'],
            ['apple', 'computers', 'Apple iPad 10th Generation 64GB', 349.00, 'tablet-green', 'iPad'],
            ['apple', 'computers', 'Apple iPad mini 6th Generation', 499.00, 'tablet-green', 'mini'],
            ['apple', 'computers', 'Apple Mac Studio M2 Max', 1999.00, 'laptop-teal', 'Studio'],
            ['apple', 'computers', 'Apple Studio Display', 1599.00, 'laptop-teal', 'Display'],
            ['dell', 'computers', 'Dell Latitude 7440 Laptop', 1299.99, 'laptop-silver', 'Latitude'],
            ['dell', 'computers', 'Dell Alienware Aurora R16 Desktop', 1799.99, 'laptop-silver', 'Aurora'],
            ['dell', 'computers', 'Dell UltraSharp U2723QE Monitor', 579.99, 'laptop-silver', 'U2723QE'],
            ['lenovo', 'computers', 'Lenovo ThinkPad T14 Gen 5', 1399.00, 'laptop-silver', 'T14'],
            ['lenovo', 'computers', 'Lenovo IdeaPad Slim 5i', 649.99, 'laptop-silver', 'IdeaPad'],
            ['hp', 'computers', 'HP Omen Transcend 14', 1499.99, 'laptop-silver', 'Omen'],
            ['hp', 'computers', 'HP EliteBook 840 G10', 1299.99, 'laptop-silver', 'Elite'],
            ['asus', 'computers', 'ASUS Vivobook S 15 OLED', 899.99, 'laptop-silver', 'Vivobook'],
            ['asus', 'computers', 'ASUS ProArt Studiobook 16 OLED', 1999.99, 'laptop-silver', 'ProArt'],
            ['acer', 'computers', 'Acer Aspire 5 15', 549.99, 'laptop-silver', 'Aspire'],
            ['acer', 'computers', 'Acer Predator Helios Neo 16', 1199.99, 'laptop-silver', 'Helios'],
            ['microsoft', 'computers', 'Microsoft Surface Laptop Studio 2', 1999.99, 'laptop-silver', 'Studio'],
            ['microsoft', 'computers', 'Microsoft Surface Go 4', 579.99, 'tablet-green', 'Go 4'],
            ['samsung', 'computers', 'Samsung Galaxy Book4 Pro', 1449.99, 'laptop-silver', 'Book4'],
            ['samsung', 'computers', 'Samsung Galaxy Tab S9 FE', 449.99, 'tablet-green', 'Tab S9'],
            ['samsung', 'computers', 'Samsung Galaxy Tab A9+', 219.99, 'tablet-green', 'Tab A9'],
            ['sony', 'audio', 'Sony LinkBuds S Earbuds', 199.99, 'earbuds-black', 'LinkBuds'],
            ['sony', 'audio', 'Sony SRS-XB100 Speaker', 59.99, 'audio-black', 'XB100'],
            ['bose', 'audio', 'Bose SoundLink Max Portable Speaker', 399.00, 'audio-black', 'Max'],
            ['bose', 'audio', 'Bose Ultra Open Earbuds', 299.00, 'earbuds-black', 'Open'],
            ['apple', 'audio', 'Apple HomePod mini', 99.00, 'audio-black', 'HomePod'],
            ['beats', 'audio', 'Beats Solo 4 Headphones', 199.99, 'audio-black', 'Solo 4'],
            ['beats', 'audio', 'Beats Studio Buds +', 169.99, 'earbuds-black', 'Buds+'],
            ['jbl', 'audio', 'JBL Xtreme 3 Speaker', 379.95, 'audio-black', 'Xtreme'],
            ['jbl', 'audio', 'JBL Go 4 Speaker', 49.95, 'audio-black', 'Go 4'],
            ['sennheiser', 'audio', 'Sennheiser Accentum Wireless Headphones', 179.95, 'audio-black', 'Accentum'],
            ['sennheiser', 'audio', 'Sennheiser HD 560S Headphones', 229.95, 'audio-black', 'HD560S'],
            ['marshall', 'audio', 'Marshall Acton III Speaker', 279.99, 'audio-black', 'Acton'],
            ['marshall', 'audio', 'Marshall Motif II A.N.C. Earbuds', 199.99, 'earbuds-black', 'Motif'],
            ['anker', 'audio', 'Anker Soundcore Space One Headphones', 99.99, 'audio-black', 'Space'],
            ['anker', 'audio', 'Anker Soundcore Boom 2 Speaker', 129.99, 'audio-black', 'Boom 2'],
            ['samsung', 'audio', 'Samsung Galaxy Buds FE', 99.99, 'earbuds-white', 'Buds FE'],
            ['lg', 'tv-home-theater', 'LG B3 55-inch OLED TV', 1299.99, 'tv-blue', 'LG B3'],
            ['lg', 'tv-home-theater', 'LG StanbyME 27-inch Smart Touch Screen', 999.99, 'tv-blue', 'StanbyME'],
            ['samsung', 'tv-home-theater', 'Samsung 77-inch S90C OLED TV', 3299.99, 'tv-blue', 'S90C'],
            ['samsung', 'tv-home-theater', 'Samsung Freestyle 2nd Gen Projector', 799.99, 'tv-blue', 'Projector'],
            ['sony', 'tv-home-theater', 'Sony Bravia Theater Bar 9', 1399.99, 'audio-black', 'Bar 9'],
            ['sony', 'tv-home-theater', 'Sony X90L 65-inch LED TV', 1199.99, 'tv-blue', 'X90L'],
            ['tcl', 'tv-home-theater', 'TCL 75-inch QM8 QLED TV', 1799.99, 'tv-blue', 'QM8'],
            ['hisense', 'tv-home-theater', 'Hisense 75-inch U8N Mini-LED TV', 1499.99, 'tv-blue', 'U8N'],
            ['amazon', 'tv-home-theater', 'Amazon Fire TV Cube 3rd Gen', 139.99, 'tablet-green', 'Cube'],
            ['amazon', 'tv-home-theater', 'Amazon Fire TV 55-inch Omni QLED', 599.99, 'tv-blue', 'Omni'],
            ['apple', 'tv-home-theater', 'Apple TV 4K Wi-Fi + Ethernet 128GB', 149.00, 'tablet-green', 'Apple TV'],
            ['google', 'tv-home-theater', 'Google Nest Cam with Floodlight', 279.99, 'camera-black', 'Nest Cam'],
            ['sony', 'gaming', 'PlayStation VR2', 549.99, 'console-white', 'PS VR2'],
            ['sony', 'gaming', 'DualSense Edge Wireless Controller', 199.99, 'console-white', 'Edge'],
            ['sony', 'gaming', 'PlayStation Pulse Elite Wireless Headset', 149.99, 'audio-black', 'Pulse'],
            ['microsoft', 'gaming', 'Xbox Elite Wireless Controller Series 2', 179.99, 'console-black', 'Elite'],
            ['microsoft', 'gaming', 'Xbox Series S 1TB', 349.99, 'console-white', 'Series S'],
            ['microsoft', 'gaming', 'Xbox Adaptive Controller', 99.99, 'console-white', 'Adaptive'],
            ['nintendo', 'gaming', 'Nintendo Switch Pro Controller', 69.99, 'gaming-red', 'Pro'],
            ['nintendo', 'gaming', 'Nintendo Switch Sports', 49.99, 'gaming-red', 'Sports'],
            ['nintendo', 'gaming', 'Nintendo Super Mario Bros. Wonder', 59.99, 'gaming-red', 'Mario'],
            ['valve', 'gaming', 'Steam Deck LCD 256GB', 399.00, 'console-black', 'Steam'],
            ['meta', 'gaming', 'Meta Quest 2 128GB', 249.99, 'console-white', 'Quest 2'],
            ['meta', 'gaming', 'Meta Quest Pro', 999.99, 'console-white', 'Quest Pro'],
            ['razer', 'gaming', 'Razer Huntsman V3 Pro Keyboard', 249.99, 'accessory-gray', 'Huntsman'],
            ['steelseries', 'gaming', 'SteelSeries Apex Pro TKL Wireless', 249.99, 'accessory-gray', 'Apex'],
            ['canon', 'cameras', 'Canon EOS R6 Mark II Mirrorless Camera', 2499.99, 'camera-silver', 'R6 II'],
            ['canon', 'cameras', 'Canon EOS R7 Mirrorless Camera', 1499.99, 'camera-silver', 'R7'],
            ['canon', 'cameras', 'Canon RF 50mm F1.8 STM Lens', 199.99, 'camera-silver', 'RF50'],
            ['sony', 'cameras', 'Sony Alpha a6700 Mirrorless Camera', 1399.99, 'camera-black', 'a6700'],
            ['sony', 'cameras', 'Sony FE 24-70mm F2.8 GM II Lens', 2299.99, 'camera-black', '24-70'],
            ['nikon', 'cameras', 'Nikon Z 8 Mirrorless Camera', 3999.95, 'camera-black', 'Z 8'],
            ['nikon', 'cameras', 'Nikon Z 50 Mirrorless Camera', 859.95, 'camera-black', 'Z 50'],
            ['nikon', 'cameras', 'Nikon NIKKOR Z 24-70mm f/4 S Lens', 999.95, 'camera-black', 'Z Lens'],
            ['fujifilm', 'cameras', 'Fujifilm X-S20 Mirrorless Camera', 1299.95, 'camera-silver', 'X-S20'],
            ['fujifilm', 'cameras', 'Fujifilm Instax Mini Evo', 199.95, 'camera-silver', 'Evo'],
            ['gopro', 'cameras', 'GoPro HERO10 Black', 299.99, 'camera-black', 'HERO10'],
            ['gopro', 'cameras', 'GoPro Media Mod', 79.99, 'camera-black', 'Mod'],
            ['insta360', 'cameras', 'Insta360 Ace Pro Action Camera', 449.99, 'camera-black', 'Ace Pro'],
            ['insta360', 'cameras', 'Insta360 Flow Smartphone Stabilizer', 159.99, 'camera-black', 'Flow'],
            ['amazon', 'e-readers', 'Kindle Colorsoft Signature Edition', 279.99, 'tablet-green', 'Color'],
            ['amazon', 'e-readers', 'Kindle Paperwhite Signature Edition', 189.99, 'tablet-green', 'Paper'],
            ['amazon', 'e-readers', 'Kindle Scribe 32GB Premium Pen', 389.99, 'tablet-green', 'Scribe'],
            ['amazon', 'e-readers', 'Kindle Voyage', 199.99, 'tablet-green', 'Voyage'],
            ['kobo', 'e-readers', 'Kobo Libra 2', 189.99, 'tablet-green', 'Libra'],
            ['kobo', 'e-readers', 'Kobo Nia', 109.99, 'tablet-green', 'Nia'],
            ['kobo', 'e-readers', 'Kobo Clara 2E', 139.99, 'tablet-green', 'Clara'],
            ['kobo', 'e-readers', 'Kobo Forma 32GB', 249.99, 'tablet-green', 'Forma'],
            ['apple', 'accessories', 'Apple AirTag 4 Pack', 99.00, 'accessory-gray', 'AirTag'],
            ['apple', 'accessories', 'Apple MagSafe Charger', 39.00, 'accessory-gray', 'MagSafe'],
            ['apple', 'accessories', 'Apple USB-C Digital AV Multiport Adapter', 69.00, 'accessory-gray', 'USB-C'],
            ['samsung', 'accessories', 'Samsung Galaxy SmartTag2', 29.99, 'accessory-gray', 'Tag2'],
            ['samsung', 'accessories', 'Samsung T9 Portable SSD 2TB', 219.99, 'accessory-gray', 'T9'],
            ['logitech', 'accessories', 'Logitech Pebble Keys 2 K380s', 39.99, 'accessory-gray', 'K380s'],
            ['logitech', 'accessories', 'Logitech MX Mechanical Keyboard', 169.99, 'accessory-gray', 'MX Mech'],
            ['logitech', 'accessories', 'Logitech StreamCam', 169.99, 'accessory-gray', 'Stream'],
            ['anker', 'accessories', 'Anker Prime 100W GaN Charger', 84.99, 'accessory-gray', 'Prime'],
            ['anker', 'accessories', 'Anker 555 USB-C Hub', 69.99, 'accessory-gray', '555'],
            ['belkin', 'accessories', 'Belkin 2-in-1 MagSafe Charging Dock', 99.99, 'accessory-gray', 'Dock'],
            ['belkin', 'accessories', 'Belkin USB-C 7-in-1 Multiport Adapter', 59.99, 'accessory-gray', '7-in-1'],
            ['sandisk', 'accessories', 'SanDisk Extreme PRO SDXC 128GB', 39.99, 'accessory-gray', 'SDXC'],
            ['sandisk', 'accessories', 'SanDisk Ultra Dual Drive Luxe USB-C 256GB', 29.99, 'accessory-gray', 'USB-C'],
            ['tp-link', 'accessories', 'TP-Link Archer AX55 Router', 129.99, 'accessory-gray', 'AX55'],
            ['tp-link', 'accessories', 'TP-Link Tapo C120 Security Camera', 39.99, 'camera-black', 'Tapo'],
            ['ubiquiti', 'accessories', 'Ubiquiti UniFi U6+ Access Point', 129.00, 'accessory-gray', 'U6+'],
            ['razer', 'accessories', 'Razer Seiren V3 Mini Microphone', 59.99, 'accessory-gray', 'Seiren'],
            ['dyson', 'home-kitchen', 'Dyson V12 Detect Slim Vacuum', 649.99, 'home-gold', 'V12'],
            ['dyson', 'home-kitchen', 'Dyson Corrale Hair Straightener', 499.99, 'home-gold', 'Corrale'],
            ['shark', 'home-kitchen', 'Shark HydroVac MessMaster', 299.99, 'home-gold', 'HydroVac'],
            ['shark', 'home-kitchen', 'Shark Wandvac Cordless Handheld Vacuum', 129.99, 'home-gold', 'Wandvac'],
            ['irobot', 'home-kitchen', 'iRobot Roomba Combo j9+', 1399.99, 'home-gold', 'Roomba'],
            ['instant-pot', 'home-kitchen', 'Instant Pot Rio 6 Quart', 99.99, 'kitchen-silver', 'Rio'],
            ['instant-pot', 'home-kitchen', 'Instant Pot Duo Crisp Ultimate Lid', 229.99, 'kitchen-silver', 'Duo'],
            ['ninja', 'home-kitchen', 'Ninja Blast Portable Blender', 59.99, 'kitchen-black', 'Blast'],
            ['ninja', 'home-kitchen', 'Ninja Foodi PossibleCooker PRO', 149.99, 'kitchen-black', 'Cooker'],
            ['kitchenaid', 'home-kitchen', 'KitchenAid Variable Speed Corded Hand Blender', 59.99, 'kitchen-silver', 'Hand'],
            ['kitchenaid', 'home-kitchen', 'KitchenAid 7 Quart Bowl-Lift Stand Mixer', 649.99, 'kitchen-silver', 'Mixer'],
            ['philips', 'home-kitchen', 'Philips Hue White and Color Ambiance Starter Kit', 199.99, 'kitchen-silver', 'Hue'],
            ['philips', 'home-kitchen', 'Philips SmartSleep Wake-Up Light', 109.99, 'kitchen-silver', 'Light'],
            ['breville', 'home-kitchen', 'Breville Bambino Plus Espresso Machine', 499.95, 'kitchen-silver', 'Bambino'],
            ['breville', 'home-kitchen', 'Breville Joule Oven Air Fryer Pro', 549.95, 'kitchen-silver', 'Joule'],
            ['ring', 'home-kitchen', 'Ring Stick Up Cam Battery', 99.99, 'camera-black', 'Ring'],
            ['arlo', 'home-kitchen', 'Arlo Essential Spotlight Camera', 129.99, 'camera-black', 'Arlo'],
            ['apple', 'wearables', 'Apple Watch Series 8 GPS 41mm', 399.00, 'watch-blue', 'Watch'],
            ['apple', 'wearables', 'Apple Watch Nike Sport Band', 49.00, 'watch-blue', 'Band'],
            ['samsung', 'wearables', 'Samsung Galaxy Watch5 Pro', 449.99, 'watch-blue', 'Watch5'],
            ['garmin', 'wearables', 'Garmin epix Pro Gen 2', 899.99, 'watch-blue', 'epix'],
            ['garmin', 'wearables', 'Garmin Vivosmart 5', 149.99, 'watch-blue', 'Vivo'],
            ['fitbit', 'wearables', 'Fitbit Sense 2', 249.95, 'watch-blue', 'Sense'],
            ['fitbit', 'wearables', 'Fitbit Ace 3', 79.95, 'watch-blue', 'Ace'],
            ['fitbit', 'wearables', 'Fitbit Ace LTE', 229.95, 'watch-blue', 'Ace LTE'],
            ['meta', 'wearables', 'Ray-Ban Meta Headliner Smart Glasses', 299.00, 'watch-blue', 'Meta'],
            ['garmin', 'wearables', 'Garmin Lily 2', 249.99, 'watch-blue', 'Lily'],
            ['lego', 'toys', 'LEGO Icons Orchid', 49.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Ideas Typewriter', 249.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Creator 3-in-1 Space Astronaut', 54.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Technic McLaren Formula 1 Race Car', 199.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Star Wars R2-D2', 99.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Harry Potter Hogwarts Castle and Grounds', 169.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Disney Walt Disney Tribute Camera', 99.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Minecraft The Crafting Table', 89.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Super Mario Piranha Plant', 59.99, 'toy-red', 'LEGO'],
            ['lego', 'toys', 'LEGO Icons Concorde', 199.99, 'toy-red', 'LEGO'],
        ]);

        return collect($items)
            ->map(function (array $item, int $index): array {
                [$brandSlug, $categorySlug, $name, $price, $imageTheme, $imageLabel] = $item;
                $stock = 5 + (($index * 7) % 42);
                $rating = 4.1 + (($index % 9) * 0.1);
                $reviewCount = 18 + (($index * 13) % 280);

                return [
                    'sku' => 'PRD-'.str_pad((string) (2001 + $index), 4, '0', STR_PAD_LEFT),
                    'name' => $name,
                    'brand_slug' => $brandSlug,
                    'category_slug' => $categorySlug,
                    'price' => $price,
                    'previous_price' => $index % 5 === 0 ? round($price * 1.12, 2) : null,
                    'stock' => $stock,
                    'rating' => min(4.9, $rating),
                    'review_count' => $reviewCount,
                    'is_featured' => $index % 37 === 0,
                    'is_new' => $index % 11 === 0,
                    'image_label' => $imageLabel,
                    'image_theme' => $imageTheme,
                    'color_name' => $this->colorForTheme($imageTheme),
                    'short_description' => $this->shortDescriptionFor($categorySlug, $name),
                    'description' => $this->descriptionFor($categorySlug, $name),
                    'shipping_weight_grams' => $this->shippingWeightFor($categorySlug),
                    'warranty_months' => $categorySlug === 'toys' ? null : 12,
                    'specifications' => $this->specificationsFor($categorySlug),
                ];
            })
            ->all();
    }

    private function shortDescriptionFor(string $categorySlug, string $name): string
    {
        return match ($categorySlug) {
            'smartphones' => $name.' with modern mobile performance, sharp cameras, and everyday 5G connectivity.',
            'computers' => $name.' for productivity, study, creative work, and everyday computing.',
            'audio' => $name.' for focused listening, calls, commuting, and entertainment.',
            'tv-home-theater' => $name.' for streaming, movies, sports, and living-room entertainment.',
            'gaming' => $name.' for console, handheld, or desktop gaming setups.',
            'cameras' => $name.' for content creation, travel, video, and everyday photography.',
            'e-readers' => $name.' for focused reading with portable storage and long battery life.',
            'accessories' => $name.' as a practical upgrade for desks, devices, and connected setups.',
            'home-kitchen' => $name.' for everyday home routines, cooking, cleaning, and convenience.',
            'wearables' => $name.' for health tracking, notifications, workouts, and daily activity.',
            'toys' => $name.' as a recognizable building set for collecting, display, and gifting.',
            default => $name.' with seeded storefront details for testing.',
        };
    }

    private function descriptionFor(string $categorySlug, string $name): string
    {
        return $this->shortDescriptionFor($categorySlug, $name).' This seeded real-world product record includes pricing, stock, ratings, review counts, and display fields for storefront testing.';
    }

    private function colorForTheme(string $imageTheme): string
    {
        return match ($imageTheme) {
            'phone-titanium' => 'Natural Titanium',
            'phone-graphite', 'audio-black', 'earbuds-black', 'console-black', 'camera-black', 'kitchen-black' => 'Black',
            'laptop-silver', 'camera-silver', 'kitchen-silver', 'accessory-gray' => 'Silver',
            'laptop-teal', 'tablet-green', 'tv-blue', 'watch-blue' => 'Blue',
            'gaming-red', 'toy-red' => 'Red',
            'earbuds-white', 'console-white' => 'White',
            default => 'Assorted',
        };
    }

    private function shippingWeightFor(string $categorySlug): int
    {
        return match ($categorySlug) {
            'smartphones', 'e-readers', 'wearables' => 220,
            'audio', 'accessories' => 450,
            'computers' => 1450,
            'tv-home-theater' => 7000,
            'gaming' => 1800,
            'cameras' => 650,
            'home-kitchen' => 4200,
            'toys' => 900,
            default => 1000,
        };
    }

    private function specificationsFor(string $categorySlug): array
    {
        return match ($categorySlug) {
            'smartphones' => ['connectivity' => '5G', 'condition' => 'New', 'warranty' => '1 year'],
            'computers' => ['storage' => 'Configurable', 'condition' => 'New', 'warranty' => '1 year'],
            'audio' => ['connection' => 'Wireless', 'condition' => 'New', 'warranty' => '1 year'],
            'tv-home-theater' => ['resolution' => '4K/Smart', 'condition' => 'New', 'warranty' => '1 year'],
            'gaming' => ['platform' => 'Gaming', 'condition' => 'New', 'warranty' => '1 year'],
            'cameras' => ['capture' => 'Photo/Video', 'condition' => 'New', 'warranty' => '1 year'],
            'e-readers' => ['display' => 'E ink', 'condition' => 'New', 'warranty' => '1 year'],
            'accessories' => ['compatibility' => 'Multi-device', 'condition' => 'New', 'warranty' => '1 year'],
            'home-kitchen' => ['use' => 'Home', 'condition' => 'New', 'warranty' => '1 year'],
            'wearables' => ['tracking' => 'Health/activity', 'condition' => 'New', 'warranty' => '1 year'],
            'toys' => ['type' => 'Building set', 'condition' => 'New', 'age' => 'Varies'],
            default => ['condition' => 'New', 'warranty' => '1 year'],
        };
    }
}
