<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::query()->pluck('id', 'slug');
        $brands = Brand::query()->pluck('id', 'slug');

        $products = [
            [
                'sku' => 'PRD-1001',
                'name' => 'Apple iPhone 15 Pro 256GB',
                'brand_slug' => 'apple',
                'category_slug' => 'smartphones',
                'price' => 1099.00,
                'previous_price' => 1199.00,
                'stock' => 12,
                'rating' => 4.8,
                'review_count' => 124,
                'is_featured' => true,
                'is_new' => false,
                'image_label' => 'iPhone',
                'image_theme' => 'phone-titanium',
                'color_name' => 'Natural Titanium',
                'short_description' => 'Titanium flagship phone with Pro camera controls and A17 Pro performance.',
                'description' => 'A premium smartphone for photography, gaming, and daily productivity with a bright display, strong battery life, and durable titanium finish.',
                'shipping_weight_grams' => 187,
                'warranty_months' => 12,
                'specifications' => ['storage' => '256GB', 'display' => '6.1-inch', 'connectivity' => '5G'],
            ],
            [
                'sku' => 'PRD-1002',
                'name' => 'Samsung Galaxy S24 Ultra',
                'brand_slug' => 'samsung',
                'category_slug' => 'smartphones',
                'price' => 1299.99,
                'previous_price' => null,
                'stock' => 10,
                'rating' => 4.7,
                'review_count' => 98,
                'is_featured' => true,
                'is_new' => true,
                'image_label' => 'S24',
                'image_theme' => 'phone-graphite',
                'color_name' => 'Titanium Gray',
                'short_description' => 'Large-screen Android flagship with S Pen, AI tools, and advanced camera zoom.',
                'description' => 'A high-end Android phone built for multitasking, note taking, editing, and sharp long-range photos.',
                'shipping_weight_grams' => 232,
                'warranty_months' => 12,
                'specifications' => ['storage' => '256GB', 'display' => '6.8-inch', 'pen' => 'S Pen included'],
            ],
            [
                'sku' => 'PRD-1003',
                'name' => 'Sony WH-1000XM5 Headphones',
                'brand_slug' => 'sony',
                'category_slug' => 'audio',
                'price' => 399.99,
                'previous_price' => null,
                'stock' => 18,
                'rating' => 4.7,
                'review_count' => 210,
                'is_featured' => true,
                'is_new' => false,
                'image_label' => 'XM5',
                'image_theme' => 'audio-black',
                'color_name' => 'Black',
                'short_description' => 'Wireless noise-canceling headphones tuned for travel and deep focus.',
                'description' => 'A lightweight over-ear headset with adaptive noise cancellation, clear calls, and long battery life.',
                'shipping_weight_grams' => 250,
                'warranty_months' => 12,
                'specifications' => ['battery' => 'Up to 30 hours', 'noise_canceling' => 'Adaptive ANC', 'fit' => 'Over-ear'],
            ],
            [
                'sku' => 'PRD-1004',
                'name' => 'Apple MacBook Air 13-inch M3',
                'brand_slug' => 'apple',
                'category_slug' => 'e-readers',
                'price' => 1099.00,
                'previous_price' => 1199.00,
                'stock' => 8,
                'rating' => 4.9,
                'review_count' => 156,
                'is_featured' => true,
                'is_new' => true,
                'image_label' => 'Air',
                'image_theme' => 'laptop-teal',
                'color_name' => 'Midnight',
                'short_description' => 'Portable M3 laptop for study, work, and everyday creative projects.',
                'description' => 'A thin, fanless laptop with excellent battery life, a sharp display, and enough performance for everyday production work.',
                'shipping_weight_grams' => 1240,
                'warranty_months' => 12,
                'specifications' => ['chip' => 'Apple M3', 'memory' => '8GB', 'storage' => '256GB SSD'],
            ],
            [
                'sku' => 'PRD-1005',
                'name' => 'Dell XPS 13 Laptop',
                'brand_slug' => 'dell',
                'category_slug' => 'accessories',
                'price' => 999.99,
                'previous_price' => null,
                'stock' => 7,
                'rating' => 4.5,
                'review_count' => 88,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'XPS',
                'image_theme' => 'laptop-silver',
                'color_name' => 'Platinum',
                'short_description' => 'Compact Windows laptop with premium build and bright display.',
                'description' => 'A sleek work laptop for browsing, spreadsheets, online classes, and travel-friendly productivity.',
                'shipping_weight_grams' => 1180,
                'warranty_months' => 12,
                'specifications' => ['display' => '13.4-inch', 'os' => 'Windows', 'storage' => '512GB SSD'],
            ],
            [
                'sku' => 'PRD-1006',
                'name' => 'Nintendo Switch OLED Model',
                'brand_slug' => 'nintendo',
                'category_slug' => 'gaming',
                'price' => 349.99,
                'previous_price' => null,
                'stock' => 15,
                'rating' => 4.8,
                'review_count' => 176,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Switch',
                'image_theme' => 'gaming-red',
                'color_name' => 'Neon Red/Blue',
                'short_description' => 'Hybrid console with vivid OLED display for TV, tabletop, and handheld play.',
                'description' => 'A flexible gaming system for family games, travel, and casual handheld sessions.',
                'shipping_weight_grams' => 420,
                'warranty_months' => 12,
                'specifications' => ['display' => '7-inch OLED', 'storage' => '64GB', 'modes' => 'TV, tabletop, handheld'],
            ],
            [
                'sku' => 'PRD-1007',
                'name' => 'Apple AirPods Pro (2nd Generation)',
                'brand_slug' => 'apple',
                'category_slug' => 'audio',
                'price' => 249.00,
                'previous_price' => null,
                'stock' => 22,
                'rating' => 4.8,
                'review_count' => 242,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Pods',
                'image_theme' => 'earbuds-white',
                'color_name' => 'White',
                'short_description' => 'Compact earbuds with active noise cancellation and spatial audio.',
                'description' => 'Everyday earbuds for calls, commuting, workouts, and seamless switching between Apple devices.',
                'shipping_weight_grams' => 61,
                'warranty_months' => 12,
                'specifications' => ['case' => 'MagSafe charging', 'noise_canceling' => 'Active ANC', 'fit' => 'In-ear'],
            ],
            [
                'sku' => 'PRD-1008',
                'name' => 'Samsung 55-inch Class QLED 4K TV',
                'brand_slug' => 'samsung',
                'category_slug' => 'tv-home-theater',
                'price' => 799.99,
                'previous_price' => 899.99,
                'stock' => 6,
                'rating' => 4.6,
                'review_count' => 73,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'QLED',
                'image_theme' => 'tv-blue',
                'color_name' => 'Black',
                'short_description' => '55-inch QLED 4K TV with bright color and smart streaming apps.',
                'description' => 'A living-room screen for movies, sports, games, and streaming with crisp 4K resolution.',
                'shipping_weight_grams' => 15800,
                'warranty_months' => 24,
                'specifications' => ['size' => '55-inch', 'resolution' => '4K UHD', 'panel' => 'QLED'],
            ],
            [
                'sku' => 'PRD-1009',
                'name' => 'Bose QuietComfort Ultra Earbuds',
                'brand_slug' => 'bose',
                'category_slug' => 'audio',
                'price' => 299.00,
                'previous_price' => null,
                'stock' => 14,
                'rating' => 4.5,
                'review_count' => 67,
                'is_featured' => false,
                'is_new' => true,
                'image_label' => 'Bose',
                'image_theme' => 'earbuds-black',
                'color_name' => 'Black',
                'short_description' => 'Premium earbuds with immersive audio and strong noise cancellation.',
                'description' => 'A travel-ready listening option for music, calls, podcasts, and quieter commutes.',
                'shipping_weight_grams' => 74,
                'warranty_months' => 12,
                'specifications' => ['audio' => 'Immersive audio', 'noise_canceling' => 'QuietComfort ANC', 'fit' => 'In-ear'],
            ],
            [
                'sku' => 'PRD-1010',
                'name' => 'GoPro HERO12 Black',
                'brand_slug' => 'gopro',
                'category_slug' => 'cameras',
                'price' => 399.99,
                'previous_price' => null,
                'stock' => 9,
                'rating' => 4.4,
                'review_count' => 59,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'HERO',
                'image_theme' => 'camera-black',
                'color_name' => 'Black',
                'short_description' => 'Durable action camera for travel, sports, and outdoor video.',
                'description' => 'A rugged camera for stabilized video, slow motion clips, and compact content capture.',
                'shipping_weight_grams' => 154,
                'warranty_months' => 12,
                'specifications' => ['video' => '5.3K', 'waterproof' => '10m', 'stabilization' => 'HyperSmooth'],
            ],
            [
                'sku' => 'PRD-1011',
                'name' => 'Kindle Paperwhite 16GB',
                'brand_slug' => 'amazon',
                'category_slug' => 'computers',
                'price' => 149.99,
                'previous_price' => null,
                'stock' => 20,
                'rating' => 4.7,
                'review_count' => 138,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Kindle',
                'image_theme' => 'tablet-green',
                'color_name' => 'Black',
                'short_description' => 'Water-resistant e-reader with glare-free display and weeks of battery.',
                'description' => 'A lightweight reading device for travel, bedtime, and focused reading without phone distractions.',
                'shipping_weight_grams' => 205,
                'warranty_months' => 12,
                'specifications' => ['storage' => '16GB', 'display' => '6.8-inch', 'water_resistant' => 'IPX8'],
            ],
            [
                'sku' => 'PRD-1012',
                'name' => 'Logitech MX Master 3S Mouse',
                'brand_slug' => 'logitech',
                'category_slug' => 'computers',
                'price' => 99.99,
                'previous_price' => null,
                'stock' => 30,
                'rating' => 4.9,
                'review_count' => 301,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'MX',
                'image_theme' => 'accessory-gray',
                'color_name' => 'Graphite',
                'short_description' => 'Ergonomic wireless mouse with quiet clicks and precision scrolling.',
                'description' => 'A productivity mouse for designers, analysts, and students who move between multiple devices.',
                'shipping_weight_grams' => 141,
                'warranty_months' => 24,
                'specifications' => ['dpi' => '8000', 'buttons' => '7', 'connectivity' => 'Bluetooth/USB receiver'],
            ],
            [
                'sku' => 'PRD-1013',
                'name' => 'PlayStation 5 Console',
                'brand_slug' => 'sony',
                'category_slug' => 'gaming',
                'price' => 499.99,
                'previous_price' => null,
                'stock' => 11,
                'rating' => 4.8,
                'review_count' => 190,
                'is_featured' => true,
                'is_new' => false,
                'image_label' => 'PS5',
                'image_theme' => 'console-white',
                'color_name' => 'White',
                'short_description' => 'Current-generation console for cinematic games and fast loading.',
                'description' => 'A home console with strong graphics performance, haptic controller feedback, and a broad game library.',
                'shipping_weight_grams' => 4500,
                'warranty_months' => 12,
                'specifications' => ['storage' => '1TB', 'resolution' => 'Up to 4K', 'controller' => 'DualSense'],
            ],
            [
                'sku' => 'PRD-1014',
                'name' => 'Xbox Series X',
                'brand_slug' => 'microsoft',
                'category_slug' => 'gaming',
                'price' => 499.99,
                'previous_price' => null,
                'stock' => 9,
                'rating' => 4.7,
                'review_count' => 112,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Xbox',
                'image_theme' => 'console-black',
                'color_name' => 'Black',
                'short_description' => 'Powerful console with Game Pass support and fast resume.',
                'description' => 'A high-performance console for 4K gaming, media streaming, and subscription game libraries.',
                'shipping_weight_grams' => 4450,
                'warranty_months' => 12,
                'specifications' => ['storage' => '1TB', 'resolution' => 'Up to 4K', 'service' => 'Game Pass ready'],
            ],
            [
                'sku' => 'PRD-1015',
                'name' => 'Dyson V15 Detect Vacuum',
                'brand_slug' => 'dyson',
                'category_slug' => 'home-kitchen',
                'price' => 749.99,
                'previous_price' => 799.99,
                'stock' => 5,
                'rating' => 4.6,
                'review_count' => 64,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'V15',
                'image_theme' => 'home-gold',
                'color_name' => 'Nickel/Yellow',
                'short_description' => 'Cordless vacuum with dust detection and powerful suction.',
                'description' => 'A premium cleaning tool for carpets, hard floors, pet hair, and quick everyday messes.',
                'shipping_weight_grams' => 3100,
                'warranty_months' => 24,
                'specifications' => ['runtime' => 'Up to 60 minutes', 'type' => 'Cordless', 'sensor' => 'Dust detection'],
            ],
            [
                'sku' => 'PRD-1016',
                'name' => 'Instant Pot Duo 7-in-1 6 Quart',
                'brand_slug' => 'instant-pot',
                'category_slug' => 'home-kitchen',
                'price' => 99.95,
                'previous_price' => null,
                'stock' => 16,
                'rating' => 4.7,
                'review_count' => 218,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Duo',
                'image_theme' => 'kitchen-silver',
                'color_name' => 'Stainless Steel',
                'short_description' => 'Multi-cooker for pressure cooking, slow cooking, rice, and steaming.',
                'description' => 'A practical kitchen appliance for meal prep, family dinners, and compact kitchens.',
                'shipping_weight_grams' => 5200,
                'warranty_months' => 12,
                'specifications' => ['capacity' => '6 quart', 'functions' => '7-in-1', 'finish' => 'Stainless steel'],
            ],
            [
                'sku' => 'PRD-1017',
                'name' => 'Ninja Foodi DualZone Air Fryer',
                'brand_slug' => 'ninja',
                'category_slug' => 'home-kitchen',
                'price' => 199.99,
                'previous_price' => null,
                'stock' => 13,
                'rating' => 4.6,
                'review_count' => 147,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'Foodi',
                'image_theme' => 'kitchen-black',
                'color_name' => 'Black',
                'short_description' => 'Dual-basket air fryer for cooking two foods at once.',
                'description' => 'A countertop cooker with two independent baskets for fast weeknight meals and snacks.',
                'shipping_weight_grams' => 8200,
                'warranty_months' => 12,
                'specifications' => ['capacity' => '8 quart', 'zones' => '2', 'finish' => 'Black'],
            ],
            [
                'sku' => 'PRD-1018',
                'name' => 'Garmin Forerunner 265',
                'brand_slug' => 'garmin',
                'category_slug' => 'wearables',
                'price' => 449.99,
                'previous_price' => null,
                'stock' => 8,
                'rating' => 4.5,
                'review_count' => 82,
                'is_featured' => false,
                'is_new' => true,
                'image_label' => '265',
                'image_theme' => 'watch-blue',
                'color_name' => 'Aqua',
                'short_description' => 'GPS running watch with AMOLED display and training readiness.',
                'description' => 'A sports watch for runners who want guided workouts, recovery data, and daily health tracking.',
                'shipping_weight_grams' => 47,
                'warranty_months' => 12,
                'specifications' => ['display' => 'AMOLED', 'gps' => 'Multi-band', 'battery' => 'Up to 13 days'],
            ],
            [
                'sku' => 'PRD-1019',
                'name' => 'Canon EOS R50 Mirrorless Camera',
                'brand_slug' => 'canon',
                'category_slug' => 'cameras',
                'price' => 679.99,
                'previous_price' => null,
                'stock' => 6,
                'rating' => 4.4,
                'review_count' => 51,
                'is_featured' => false,
                'is_new' => true,
                'image_label' => 'R50',
                'image_theme' => 'camera-silver',
                'color_name' => 'Black',
                'short_description' => 'Compact mirrorless camera for creators, travel, and family photos.',
                'description' => 'A lightweight interchangeable-lens camera with sharp autofocus and strong video features.',
                'shipping_weight_grams' => 375,
                'warranty_months' => 12,
                'specifications' => ['sensor' => 'APS-C', 'video' => '4K', 'lens' => 'RF-S mount'],
            ],
            [
                'sku' => 'PRD-1020',
                'name' => 'LEGO Icons Bouquet of Roses',
                'brand_slug' => 'lego',
                'category_slug' => 'toys',
                'price' => 59.99,
                'previous_price' => null,
                'stock' => 24,
                'rating' => 4.9,
                'review_count' => 89,
                'is_featured' => false,
                'is_new' => false,
                'image_label' => 'LEGO',
                'image_theme' => 'toy-red',
                'color_name' => 'Red',
                'short_description' => 'Decorative building set with rose stems for gifting or display.',
                'description' => 'A relaxing creative set for adults and older builders who want a colorful display piece.',
                'shipping_weight_grams' => 760,
                'warranty_months' => null,
                'specifications' => ['pieces' => '822', 'age' => '18+', 'theme' => 'Icons'],
            ],
        ];

        foreach ($products as $product) {
            $categorySlug = $product['category_slug'];
            $brandSlug = $product['brand_slug'];

            unset($product['category_slug'], $product['brand_slug']);

            $product['category_id'] = $categories[$categorySlug] ?? null;
            $product['brand_id'] = $brands[$brandSlug] ?? null;
            $product['category'] = Category::query()->whereKey($product['category_id'])->value('name') ?? 'Uncategorized';
            $product['brand'] = Brand::query()->whereKey($product['brand_id'])->value('name') ?? 'Generic';
            $product['return_window_days'] = 30;
            $product['published_at'] = now()->subDays(7);
            $product['is_active'] = true;

            Product::query()->updateOrCreate(
                ['sku' => $product['sku']],
                $product,
            );
        }
    }
}
